// <auto-generated />
namespace SchedulerUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Schedules3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Schedules3));
        
        string IMigrationMetadata.Id
        {
            get { return "202006261054062_Schedules3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
